Pradeep Website/kjp_enterprise/kjp_app/urls.py
from django.urls import path
from kjp_app import views

app_name = 'kjp_app'

urlpatterns = [
        path('add_clients',views.add_clients,name='add_clients'),
        path('view_clients',views.view_clients,name='view_clients'),
]

Pradeep Website/kjp_enterprise/kjp_enterprise/urls.py
from django.contrib import admin
from django.urls import path,include
from kjp_app import views

urlpatterns = [
    path('',views.home,name='home'),
    path('kjp_app/',include('kjp_app.urls')),
    path('admin/', admin.site.urls),
]

Pradeep Website/kjp_enterprise/kjp_app/models.py
from django.db import models
from django.core import validators

# Create your models here.

class AddClientsModel(models.Model):
    client_name = models.CharField(max_length=100)
    client_designation = models.CharField(max_length=100)
    client_job_location = models.CharField(max_length=100)
    client_phone_num = models.CharField(max_length=100,unique=True)

Pradeep Website/kjp_enterprise/kjp_app/forms.py
from django import forms
from kjp_app.models import AddClientsModel
from django.core import validators

def len_job_location(value):
    if len(value) < 2:
        raise forms.ValidationError("Must be more than one character")

def ph_num_isdig(value):
    if not(value.isdigit()):
        raise forms.ValidationError("Alphabets are not allowed")


class AddClientsForm(forms.ModelForm):
    client_job_location = forms.CharField(max_length=100,validators=[len_job_location,])
    client_phone_num = forms.CharField(max_length=100,validators=[validators.MaxLengthValidator(10),ph_num_isdig])

    class Meta():
        model = AddClientsModel
        fields = '__all__'

Pradeep Website/kjp_enterprise/kjp_app/views.py
from django.shortcuts import render
from kjp_app.forms import AddClientsForm
from kjp_app.models import AddClientsModel
from kjp_app import templatetags

# Create your views here.

def home(request):
    return render(request,'kjp_app/home.html')

def add_clients(request):
    form = AddClientsForm()

    if request.method == 'POST':
        form = AddClientsForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
        else:
            print('Form is invalid')

    return render(request,'kjp_app/add_clients.html',{'form':form})

def view_clients(request):
    client_list = AddClientsModel.objects.order_by('client_name')
    client_dict = {'client_rec': client_list}
    return render(request,'kjp_app/view_clients.html',context=client_dict)

Pradeep Website/kjp_enterprise/templates/kjp_app/add_clients.html
{% extends 'kjp_app/base.html' %}
{% block body_block %}
	 <div class="jumbotron">
	    <h3>Please Fill the client details and Submit </h3>
  </div>
  <div>
    <form method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" name="" value="Submit">
    </form>
  </div>
{% endblock %}

Pradeep Website/kjp_enterprise/templates/kjp_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css\client.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">KJP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'kjp_app:add_clients' %}">Add Clients <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'kjp_app:view_clients' %}">View Clients <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>
  </body>
</html>

Pradeep Website/kjp_enterprise/templates/kjp_app/home.html
{% extends 'kjp_app/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h2>Welcome to KJP ENTERPRISE!!! Kindly use Navigation bar to add or view clients </h2>
    </div>
{% endblock %}

Pradeep Website/kjp_enterprise/templates/kjp_app/view_clients.html
  {% extends 'kjp_app/base.html' %}
  {% load myfilters %}
  {% block body_block %}
      <div class="jumbotron">
        <h3>Please Find the client details below</h3>
      </div>
      <div style="overflow-x:auto;">
        <table>
          <tr class="table-primary">
            <th>Client Name</th>
            <th>Client Designation</th>
            <th>Client Job Location</th>
            <th>Client Phone Number</th>
          </tr>
          {% if client_rec %}
              {% for rec in client_rec %}
                  <tr class="table-success">
                    <td>{{ rec.client_name|nam_cap }}</td>
                    <td>{{ rec.client_designation|rep_slash }}</td>
                    <td>{{ rec.client_job_location|nam_cap }}</td>
                    <td>{{ rec.client_phone_num }}</td>
                  </tr>
                {% endfor%}
            {% endif %}
        </table>
      </div>
  {% endblock %}